apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-app
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - mydomain.com
      secretName: my-tls-secret
  rules:
  - host: mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-app
            port:
              number: 80
